### ISSUE TITLE
demo broken

### ISSUE THREAD

**Issue by karussell** [ellenhp/airmail#19]
it seems at the moment the demo is broken: https://airmail.rs/#demo-section

(it seems the request fails with a PR_END_OF_FILE_ERROR)

**Comment by ellenhp** [comment]
I'm not sure what's going on there actually. Speaking of the demo, I feel like I should move the demo over to a block-storage configuration because 10s latencies on the demo isn't a good look. Airmail is capable of 50-100ms typo-tolerant responses on machines with constrained resources and that feels like a cool thing to show off instead of the ultra-low-cost deployment configuration. I think the build is broken currently and I've had very little time for this project in general so I'm not sure I'll get to this soon, but thank you for the report.

**Comment by ellenhp** [comment]
I'm self-hosting the demo's api server now. For now the index is just Australia but I'm running a planet index overnight and I'll switch over the demo deployment in the morning.

**Comment by ellenhp** [comment]
Planet demo is up!
